name: matrix

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
      - name: Install Dependencies (for ${{ matrix.platform }})
        run: |
          sudo apt update
          sudo apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev

      - name: base.json import (for ${{ matrix.platform }})
        run: |
          (cd data && npm i)

      - name: Generate Job URL
        id: generate-url
        run: |
          JOB_ID=$(echo $GITHUB_JOB)
          echo "::set-output name=job-url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${JOB_ID}"

      - name: JOB URL (for ${{ matrix.platform }})
        run: |
          echo "${{ steps.generate-url.outputs.job-url }}"
